# Generated by Django 5.0.2 on 2024-02-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('vaqt', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=40)),
                ('tel_raqam', models.CharField(max_length=40)),
                ('manzil', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=39)),
                ('raqam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('narx', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tel_raqam', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=40)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.guruh')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField()),
                ('chegirma', models.PositiveIntegerField()),
                ('qarz', models.FloatField()),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.guruh')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='ustoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.ustoz'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='xona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.xona'),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.yonalish'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='yonalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.yonalish'),
        ),
    ]
