# Generated by Django 5.0.2 on 2024-02-21 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tizim', '0002_alter_guruh_xona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guruh',
            name='xona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tizim.xona'),
        ),
    ]
