# Generated by Django 5.0.2 on 2024-02-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tizim', '0003_alter_guruh_xona'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='yonalish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tizim.yonalish'),
        ),
    ]
